[opener]
edit = [
{ run = 'bat --paging=always %s',                desc = "bat", for = "linux" },
{ run = 'bat --paging=always %s', block = true, desc = "bat", for = "windows" },
{ run = 'nvim %s', block = true , for="unix"},
{ run = 'nvim %s', block = true , for="windows"},
{ run = '${EDITOR:-vi} %s', desc = "$EDITOR", block = true, for = "unix" },
{ run = 'code %s',    orphan = true, desc = "code",           for = "windows" },
{ run = 'code -w %s', block = true,  desc = "code (block)",   for = "windows" },
]
extract = [
 { run = 'ya pub extract --list %s',    desc = "Extract here", for = "unix" },
 { run = 'ya pub extract --list %s',   desc = "Extract here", for = "windows" },
]

[mgr]
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
scrolloff = 5

[preview]
tab_size = 4
wrap = "no"
